export const SmashCharacters = [
    'Bowser',
    'CaptainFalcon',
    'DonkeyKong',
    'DrMario',
    'Falco',
    'Fox',
    'Ganondorf',
    'IceClimbers',
    'Jigglypuff',
    'Kirby',
    'Link',
    'Luigi',
    'Mario',
    'Marth',
    'Mewtwo',
    'MrGameAndWatch',
    'Ness',
    'Peach',
    'Pichu',
    'Pikachu',
    'Roy',
    'Samus',
    'Sheik',
    'Yoshi',
    'YoungLink',
    'Zelda',
];

export const SlippiCharacterColors = {
    Bowser: '#376218',
    CaptainFalcon: '#c51620',
    DonkeyKong: '#2f1003',
    DrMario: '#d1cfc9',
    Falco: '#494fd6',
    FOX: '#ffb242',
    Ganondorf: '#91763e',
    IceClimbers: '#8a63ff',
    Jigglypuff: '#ffd6f0',
    Kirby: '#ffbed8',
    Link: '#073f07',
    Luigi: '#10b91a',
    Mario: '#ff1d1c',
    Marth: '#2f3955',
    Mewtwo: '#734c60',
    MrGameAndWatch: '#000000',
    Ness: '#f9ca58',
    Peach: '#ff5488',
    Pichu: '#ffff1b',
    Pikachu: '#ffff00',
    Roy: '#962000',
    Samus: '#da490c',
    Sheik: '#828681',
    Yoshi: '#008000',
    YoungLink: '#009e01',
    Zelda: '#ff6ac8',
};
